# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release /p:CI=true --no-restore
      - name: Test
        run: dotnet test LibHaru.Tests\LibHaru.Tests.csproj-c Release --logger trx --logger GitHubActions --results-directory ./test-results/ /p:CI=true
      - name: .NET Test Results
        uses: dorny/test-reporter@v2
        continue-on-error: true
        if: success() || failure()
        with:
          name: .NET Test Results
          path: 'test-results/*.trx'
          reporter: dotnet-trx        